on:
  push:
    branches:
      - masterXXXXXnope

jobs:
  build_to_dist:
    name: Copy and build to dist
    runs-on: ubuntu-latest
    steps:
      - name: Clean dist branch
        uses: actions/checkout@v2
        with:
          ref: dist
      - run: rm -rf *
      - name: Checkout master branch
        uses: actions/checkout@master
      - name: Merge master -> dist
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: master
          target_branch: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout dist branch
        uses: actions/checkout@v2
        with:
          ref: dist
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build
        run: |
          npm ci
          npm run build
          shopt -s extglob
          rm -rf !(dist)
          mv ./dist/* .
          rm -d dist
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build
          branch: dist
